OPER_(ADD, "ADDE",       (val1 + val2))
OPER_(SUB, "SUBTRAHE",   (val1 - val2))
OPER_(MUL, "MULTIPLICA", (val1 * val2))
OPER_(DIV, "DIVIDE",     (val1 / val2))
OPER_(DEG, "POTENTIA",   (pow(val1, val2)))
OPER_(SIN, "OBLIQUATIO", (sin(val1)))
OPER_(COS, "ADIACENTIA", (cos(val1)))
OPER_(SQRT, "RADIX",     (sqrt(val1)))

OPER_(IF,    "SI",    (0))
OPER_(WHILE, "DUM",   (0))
OPER_(RET,   "REDDE", (0))

OPER_(EQ,         "AEQUALIS?",           (val1 == val2))
OPER_(NOT_EQ,     "NON_EST_AEQUALIS?",   (val1 != val2))
OPER_(LESS,       "MINOR?",              (val1 < val2))
OPER_(LESS_EQ,    "MINOR_VEL_AEQUALIS?", (val1 <= val2))
OPER_(GREATER,    "MAIOR?",              (val1 > val2))
OPER_(GREATER_EQ, "MAIOR_VEL_AEQUALIS?", (val1 >= val2))
OPER_(AND,        "ET",                  (val1 && val2))
OPER_(OR,         "VEL",                 (val1 || val2))

OPER_(BLOCK_OPEN, "LAUS_MACHINA", (0))
OPER_(BLOCK_END,  "AMEN",         (0))
OPER_(COMMA,      "ET",           (0))
OPER_(L_BRACKET,  "INCEPIT",      (0))
OPER_(R_BRACKET,  "FINIS",        (0))
OPER_(LINE_END,   "PAX_MACHINA",  (0))
OPER_(ASSIGN,     "EST",          (0))
OPER_(INIT,       "SIGNIFICANS",  (0))